### ISSUE TITLE
Crafting Recipe Mega-Issue

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#63]
Mega-issue for all missing or broken crafting recipes.
 - [x] Concrete powder recipes should be shapeless
 - [x] Flux
 - [x] Saw recipes don't accept damaged saws

**Comment by alcatrazEscapee** [comment]
More info on saw recipes. Using ore dictionary ingredients doesn't respect wildcards, see here:
<https://github.com/MinecraftForge/MinecraftForge/issues/4557>. That says it is fixed, I am not seeing it. If this can't be fixed, it may be worth moving it to a container item implementation instead of `IRecipeFactory`

**Comment by Red3Tango** [comment]
Missing: Stone Knife variants

**Comment by alcatrazEscapee** [comment]
- [ ] Replace `vanilla/iron_bars` with anvil recipe.
 - [ ] `vanilla/redstone/comparator` outputs a lapis block
 - [ ] `vanilla/redstone/piston` should use ore dict for wrought iron tuyere
 - [ ] `vanilla/redstone/tripwire_hook` should use ore dict for wrought iron ingot

Verify / Discuss
 - [ ] Recipes using nether quartz are using the ore dict `gem` instead, is this intended?
 - [ ] Is a tuyere a good item to use a crafting ingredient in the place of a metal "rod / stick" item as per most other mods? A tuyere is supposed to be hollow...

**Comment by alcatrazEscapee** [comment]
- [ ] Support beams are missing a recipe - they need a new `ShapedDamageRecipe` implementation

**Comment by alcatrazEscapee** [comment]
Everything here is done - anything else can receive a separate issue as I believe most of the issues from the mega recipe PR have been solved.

**Comment by Jummit** [comment]
Saw recipes don't accept damaged saws is still an issue in 7657f0bec.
